[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
clap = { version = "4.5.17", features = ["derive"] }
http = "1.1.0"
orgize = "0.10.0-alpha.10"
serde = "1.0.210"
serde_json = "1.0.128"
tantivy = "0.22.0"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5.0", features = ["trace", "cors", "fs"] }
